---
#------------------------------------------------------------------------------
# Server Configurations
#
server:
  port: 8081
  error:
    whitelabel:
      enabled: false

#------------------------------------------------------------------------------
# MySQL Database config
#
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    # TODO: ADJUST HOST, PORT AND USER+PW HERE
    url: jdbc:mysql://${MYSQL_HOST:<HOST>}:<PORT>/db_springreact?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: <MySQL-user>
    password: <MySQL-password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: '/api'

  #------------------------------------------------------------------------------
  # OAuth2 Authorization Servers
  #
  security:
    oauth2:
      client:
        registration:
          google:
            # TODO: ADJUST YOUR GOOGLE CLIENT CREDENTIALS
            client-id: <your-client-id>
            client-secret: <your-client-secret>
#------------------------------------------------------------------------------
# MySQL Enable Logging DEBUG
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace
