---
#------------------------------------------------------------------------------
# Server Configurations
#
server:
  port: 8081
  error:
    whitelabel:
      enabled: false

#------------------------------------------------------------------------------
# MySQL Database config
#
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: '/api'

  #------------------------------------------------------------------------------
  # OAuth2 Authorization Servers
  #
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
#------------------------------------------------------------------------------
# MySQL Enable Logging DEBUG
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace
